name: Build Windows App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_Freeze
          pip install -r requirem_win.txt

      - name: Build application using cx_Freeze
        run: python setup.py build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: QtBeets
          path: ./build/*
