name: SonarQube Analysis

on: [push]

jobs:
  sonar:
    runs-on: ubuntu-latest
    services:
      sonarqube:
        image: sonarqube:community
        ports:
          - 9000:9000
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for better analysis
      
      - name: Set up JDK 17
        id: setup-java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          
      - name: Verify Java version
        run: java -version
        
      - name: Wait for SonarQube to be ready
        run: |
          until curl -s http://localhost:9000/api/system/status | grep -q "UP"; do
            echo "Waiting for SonarQube server to be ready..."
            sleep 5
          done
          
      - name: Set up SonarScanner
        run: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
            unzip sonar-scanner-cli-5.0.1.3006-linux.zip
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
            SONAR_HOST_URL: "http://localhost:9000"
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}