name: SonarQube Analysis

on: [push]

jobs:
  sonar:
    runs-on: ubuntu-latest
    services:
      sonarqube:
        image: sonarqube:community
        ports:
          - 9000:9000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Wait for SonarQube to be ready
        run: |
          until curl -s http://localhost:9000/api/system/status | grep -q "UP"; do
            echo "Waiting for SonarQube server to be ready..."
            sleep 10
          done

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: "http://localhost:9000"
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=harley029_PyQt_Advanced_Music_Player
            -Dsonar.projectName="PyQt_Advanced_Music_Player"
